version: "3.8"

services:
  web:
    build: PATH_TO_CELESTIAL
    environment:
      - PORT=4000
      - NODE_ENV=development
      - TZ=Asia/Kolkata
      - REDIS_PASSWORD=
    volumes:
      - type: bind
        source: PATH_TO_CELESTIAL
        target: /app
    networks: 
      - indieweb
      - internal
    ports:
      - "4000:4000"
    depends_on: 
      - redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    networks:
      - internal
    volumes:
      - redis:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
  indiekit:
    build: PATH_TO_INDIEKIT
    environment:
      - PORT=3000
      - NODE_ENV=development
      - TZ=IANA_TIMEZONE
      - GITHUB_REPO=THE_REPO_TO_PUBLISH_TO
      - GITHUB_TOKEN=ACCESS_TOKEN_FROM_GITHUB
      - GITHUB_USER=YOUR_GITHUB_USERNAME
      - GITHUB_BRANCH=THE_REPO_BRANCH_TO_PUBLISH_TO
      - INDIEKIT_CONFIG_PATH=
      - INDIEKIT_LOCALE=
      - INDIEKIT_URL=
    networks:
      - indieweb
    volumes:
      - type: bind
        source: PATH_TO_INDIEKIT
        target: /app
    ports:
      - "3000:3000"

volumes:
  redis:

networks: 
  indieweb:
  internal: