version: "3.8"

services:
  web:
    build: ./
    environment:
      - PORT=4000
      - NODE_ENV=development
      - TZ=Asia/Kolkata
      - REDIS_PASSWORD=Sp4cPXot9awS5kWNteB3hr
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - "4000:4000"
    depends_on: 
      - redis
  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

volumes:
  node_modules:
    external: true
  redis: