version: "3.8"

services:
  celestial:
    image: hirusi/celestial:0.12.3
    environment: 
      - PORT=4000
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      - REDIS_URL=redis://db0:RANDOMLY_GENERATED_PASSWORD@redis:6379
    networks: 
      - indieweb
      - internal
    ports:
      - "4000:4000"
    depends_on: 
      - redis
  redis:
    image: redis:6
    environment: 
      - REDIS_PASSWORD=RANDOMLY_GENERATED_PASSWORD
    ports:
      - "6379:6379"
    networks:
      - internal
    volumes:
      - redis:/data
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: sh -c "exec redis-server /usr/local/etc/redis/redis.conf --requirepass \"$${REDIS_PASSWORD}\""
  indiekit:
    build: PATH_TO_INDIEKIT
    environment:
      - PORT=3000
      - NODE_ENV=production
      - TZ=Asia/Kolkata
      - GITHUB_REPO=
      - GITHUB_TOKEN=
      - GITHUB_USER=
      - GITHUB_BRANCH=
      - INDIEKIT_CONFIG_PATH=
      - INDIEKIT_LOCALE=
      - INDIEKIT_URL=
    networks:
      - indieweb
    ports:
      - "3000:3000"

volumes:
  redis:

networks: 
  indieweb:
  internal:
